// Placeholder schema. Regenerated by `pnpm db:types` after Task 11 migration runs.
// Until then, callers should treat clients as untyped (`SupabaseClient` without
// the Database generic) when querying real tables.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
